-- ANIMAL_HOSPITALS 테이블 생성
CREATE TABLE ANIMAL_HOSPITALS (
    hospital_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    management_no VARCHAR2(50) UNIQUE,
    business_name VARCHAR2(200) NOT NULL,
    road_address VARCHAR2(500),
    jibun_address VARCHAR2(500),
    phone VARCHAR2(20),
    road_postal_code VARCHAR2(10),
    jibun_postal_code VARCHAR2(10),
    latitude NUMBER(10,7),
    longitude NUMBER(10,7),
    epsg5174_x VARCHAR2(50),
    epsg5174_y VARCHAR2(50),
    business_status VARCHAR2(20),
    business_status_code VARCHAR2(10),
    detailed_status VARCHAR2(20),
    detailed_status_code VARCHAR2(10),
    license_date DATE,
    closed_date DATE,
    suspended_start_date DATE,
    suspended_end_date DATE,
    reopened_date DATE,
    city VARCHAR2(50),
    district VARCHAR2(50),
    area_size VARCHAR2(100),
    employee_count NUMBER,
    data_source VARCHAR2(50) DEFAULT '공공데이터포털',
    data_update_type VARCHAR2(10),
    data_update_date TIMESTAMP,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);

-- 인덱스 생성
CREATE INDEX idx_business_status ON ANIMAL_HOSPITALS(business_status);
CREATE INDEX idx_city_district ON ANIMAL_HOSPITALS(city, district);
CREATE INDEX idx_coordinates ON ANIMAL_HOSPITALS(latitude, longitude);

-- 시퀀스 생성 (필요한 경우)
-- CREATE SEQUENCE ANIMAL_HOSPITALS_SEQ START WITH 1 INCREMENT BY 1;

-- 테이블 코멘트
COMMENT ON TABLE ANIMAL_HOSPITALS IS '동물병원 정보';
COMMENT ON COLUMN ANIMAL_HOSPITALS.hospital_id IS '병원 ID';
COMMENT ON COLUMN ANIMAL_HOSPITALS.management_no IS '관리번호';
COMMENT ON COLUMN ANIMAL_HOSPITALS.business_name IS '사업장명';
COMMENT ON COLUMN ANIMAL_HOSPITALS.road_address IS '도로명주소';
COMMENT ON COLUMN ANIMAL_HOSPITALS.jibun_address IS '지번주소';
COMMENT ON COLUMN ANIMAL_HOSPITALS.phone IS '전화번호';
COMMENT ON COLUMN ANIMAL_HOSPITALS.road_postal_code IS '도로명우편번호';
COMMENT ON COLUMN ANIMAL_HOSPITALS.jibun_postal_code IS '지번우편번호';
COMMENT ON COLUMN ANIMAL_HOSPITALS.latitude IS '위도 (WGS84)';
COMMENT ON COLUMN ANIMAL_HOSPITALS.longitude IS '경도 (WGS84)';
COMMENT ON COLUMN ANIMAL_HOSPITALS.epsg5174_x IS '원본 좌표X (EPSG5174)';
COMMENT ON COLUMN ANIMAL_HOSPITALS.epsg5174_y IS '원본 좌표Y (EPSG5174)';
COMMENT ON COLUMN ANIMAL_HOSPITALS.business_status IS '영업상태명';
COMMENT ON COLUMN ANIMAL_HOSPITALS.business_status_code IS '영업상태구분코드';
COMMENT ON COLUMN ANIMAL_HOSPITALS.detailed_status IS '상세영업상태명';
COMMENT ON COLUMN ANIMAL_HOSPITALS.detailed_status_code IS '상세영업상태코드';
COMMENT ON COLUMN ANIMAL_HOSPITALS.license_date IS '인허가일자';
COMMENT ON COLUMN ANIMAL_HOSPITALS.closed_date IS '폐업일자';
COMMENT ON COLUMN ANIMAL_HOSPITALS.suspended_start_date IS '휴업시작일자';
COMMENT ON COLUMN ANIMAL_HOSPITALS.suspended_end_date IS '휴업종료일자';
COMMENT ON COLUMN ANIMAL_HOSPITALS.reopened_date IS '재개업일자';
COMMENT ON COLUMN ANIMAL_HOSPITALS.city IS '시도명';
COMMENT ON COLUMN ANIMAL_HOSPITALS.district IS '시군구명';
COMMENT ON COLUMN ANIMAL_HOSPITALS.area_size IS '소재지면적';
COMMENT ON COLUMN ANIMAL_HOSPITALS.employee_count IS '총직원수';
COMMENT ON COLUMN ANIMAL_HOSPITALS.data_source IS '데이터 출처';
COMMENT ON COLUMN ANIMAL_HOSPITALS.data_update_type IS '데이터갱신구분';
COMMENT ON COLUMN ANIMAL_HOSPITALS.data_update_date IS '데이터갱신일자';
COMMENT ON COLUMN ANIMAL_HOSPITALS.created_at IS '생성일시';
COMMENT ON COLUMN ANIMAL_HOSPITALS.updated_at IS '수정일시';

-- 테이블 생성 확인
SELECT * FROM USER_TABLES WHERE TABLE_NAME = 'ANIMAL_HOSPITALS';

-- 데이터 건수 확인
SELECT COUNT(*) FROM ANIMAL_HOSPITALS;