-- DuoPet 입양 도메인 스키마 업데이트
-- 작성일: 2025-07-13
-- 작성자: DuoPet AI Assistant

-- 1. 테이블명 변경 (옵션 - 프로젝트 규칙에 따라 적용)
-- ALTER TABLE SHELTER_ANIMALS RENAME TO TB_SHELTER_ANIMALS;
-- ALTER SEQUENCE SEQ_SHELTER_ANIMALS RENAME TO SEQ_TB_SHELTER_ANIMALS;

-- 2. 공공 API 보호소 정보 컬럼 추가
ALTER TABLE SHELTER_ANIMALS ADD (
    API_SHELTER_NAME VARCHAR2(200),
    API_SHELTER_TEL VARCHAR2(50),
    API_SHELTER_ADDR VARCHAR2(500)
);

-- 3. 컬럼 설명 추가
COMMENT ON COLUMN SHELTER_ANIMALS.API_SHELTER_NAME IS '공공 API 보호소명 (FK 매핑 전 임시 저장)';
COMMENT ON COLUMN SHELTER_ANIMALS.API_SHELTER_TEL IS '공공 API 보호소 전화번호';
COMMENT ON COLUMN SHELTER_ANIMALS.API_SHELTER_ADDR IS '공공 API 보호소 주소';

-- 4. 기존 데이터 마이그레이션 (필요시)
-- status 필드가 있다면 processState로 마이그레이션
-- UPDATE SHELTER_ANIMALS 
-- SET PROCESS_STATE = CASE 
--     WHEN STATUS = 'AVAILABLE' THEN 'protect'
--     WHEN STATUS = 'PENDING_ADOPTION' THEN 'protect'
--     WHEN STATUS = 'NOT_AVAILABLE' THEN 'adopt'
--     ELSE PROCESS_STATE
-- END
-- WHERE STATUS IS NOT NULL;

-- 5. 인덱스 생성 (성능 최적화)
CREATE INDEX IDX_SHELTER_ANIMALS_PROCESS_STATE ON SHELTER_ANIMALS(PROCESS_STATE);
CREATE INDEX IDX_SHELTER_ANIMALS_API_SHELTER ON SHELTER_ANIMALS(API_SHELTER_NAME);

-- 6. 통계 정보 갱신
EXEC DBMS_STATS.GATHER_TABLE_STATS('DUOPET', 'SHELTER_ANIMALS');

-- 롤백 스크립트
-- ALTER TABLE SHELTER_ANIMALS DROP COLUMN API_SHELTER_NAME;
-- ALTER TABLE SHELTER_ANIMALS DROP COLUMN API_SHELTER_TEL;
-- ALTER TABLE SHELTER_ANIMALS DROP COLUMN API_SHELTER_ADDR;
-- DROP INDEX IDX_SHELTER_ANIMALS_PROCESS_STATE;
-- DROP INDEX IDX_SHELTER_ANIMALS_API_SHELTER;